from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    b=p.chromium.launch(executable_path='/opt/pw-browsers/chromium-1194/chrome-linux/chrome')
    pg=b.new_page(viewport={'width':412,'height':915},device_scale_factor=2)
    errs=[];pg.on('pageerror',lambda e: errs.append(str(e)))
    pg.goto('file:///home/user/Last-Bell/lab.html'); pg.wait_for_timeout(3500)
    pg.screenshot(path='lab1.png')
    pg.click('text=Pick'); pg.wait_for_timeout(300)
    pg.select_option('.labset .labf:nth-of-type(3) select:nth-of-type(1)', 's2')
    pg.select_option('.labset .labf:nth-of-type(4) select:nth-of-type(1)', 's4')
    pg.click('text=New fight'); pg.wait_for_timeout(3000)
    pg.screenshot(path='lab2.png')
    print(pg.evaluate("document.querySelector('.labwho').innerText"))
    pg.evaluate("FX.speed=4; F.f[1].head=1; F.f[1].headMax=1")
    pg.wait_for_function("document.querySelector('h2')", timeout=120000)
    pg.wait_for_timeout(500); pg.screenshot(path='lab3.png', full_page=True)
    print(pg.evaluate("document.querySelector('h2').innerText"))
    pg.click('text=Rematch'); pg.wait_for_timeout(1500)
    print('rematch ok', pg.evaluate("!!document.querySelector('#cv')"))
    print('errs',errs[:5]); b.close()
